# 服務配置
server:
  port: 21090
  servlet:
    context-path: /api/book-manage-sys-api/v1.0

# API 地址前綴，用於接口攔截放行
my-server:
  api-context-path: /api/book-manage-sys-api/v1.0

# MySQL 與檔案上傳限制配置  local:如果有application-local.yml會將application-local.yml文件覆蓋到這裡  雲端DB不能寫死application-local.yml不能上傳git
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





