# 服務配置
#  如果有環境變數 PORT（Render 會傳入） → 使用這個值（正確的埠口 ✅）
#  如果在本地執行（沒有設定 PORT） → 就用 21090 方便開發
server:
  port: ${PORT:21090}
  servlet:
    context-path: /api/book-manage-sys-api/v1.0

# API 地址前綴，用於接口攔截放行 與 檔案上傳
my-server:
  api-context-path: https://booksystem-jgi1.onrender.com/api/book-manage-sys-api/v1.0
#  /api/book-manage-sys-api/v1.0

# MySQL 與檔案上傳限制配置  local:如果有application-local.yml會將application-local.yml文件覆蓋到這裡  雲端DB不能寫死application-local.yml不能上傳git
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=Asia/Taipei
      username: ${DB_USER}
      password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





